# Generated by Django 5.2.3 on 2025-06-14 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_bot.service', verbose_name='услуга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(verbose_name='услуга'),
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together={('service', 'min_objects')},
        ),
    ]
