# Generated by Django 5.2.3 on 2025-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot', '0002_discount_service_alter_service_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='min_objects',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='минимальное количество объектов'),
        ),
    ]
