# Generated by Django 5.2.3 on 2025-06-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_bot', '0003_alter_discount_min_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='min_objects',
            field=models.FloatField(verbose_name='минимальное количество объектов'),
        ),
    ]
