# Generated by Django 5.2.3 on 2025-12-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('name', models.CharField(blank=True, default='user', max_length=30, null=True, verbose_name='Имя')),
                ('text', models.TextField(max_length=200, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['date'],
            },
        ),
    ]
