# Generated by Django 5.2.3 on 2025-12-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка'),
        ),
    ]
