# Generated by Django 5.2.3 on 2025-12-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео URL'),
        ),
    ]
