# Generated by Django 5.2.3 on 2026-01-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_photo_video_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Юр.лица',
                'verbose_name_plural': 'Юр.лица',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Физ.лица',
                'verbose_name_plural': 'Физ.лица',
            },
        ),
    ]
