# Generated by Django 5.2.3 on 2026-01-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_organizations_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
    ]
