# Generated by Django 5.2.3 on 2026-01-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_people_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='image',
        ),
        migrations.AddField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='OrganizationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organization_photos', verbose_name='Фото')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='general.organizations')),
            ],
            options={
                'verbose_name': 'Юр.лица фото',
                'verbose_name_plural': 'Юр.лица фото',
            },
        ),
    ]
