# Generated by Django 5.2.3 on 2026-01-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_remove_organizations_image_people_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, verbose_name='заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
